### ISSUE TITLE
Update json version

### ISSUE THREAD

**Issue by sagar18041** [girishso/goog_currency#2]
The json version for this gem is - json (~> 1.7.5) ruby.
and the devise json version is - json (1.8.0)
so when i do bundle it gives me error 
`Bundler could not find compatible versions for gem "json":
  In Gemfile:
    goog_currency (>= 0) ruby depends on
      json (~> 1.7.5) ruby

```
devise (>= 0) ruby depends on
  json (1.8.0)`
```

**Comment by girishso** [comment]
Specific json gem version requirement is removed in v1.0.0.
